name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Github Action
      uses: actions/checkout@master

    - name: Use proper .NET version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Run tests
      working-directory: src
      run: dotnet test
      env:
        NgrokOptions__AuthToken: ${{ secrets.NgrokOptionsAuthToken }}
